/**
 * `i18n:sync` writes a lot: the fill half hands ~2k English keys to every
 * target locale, so before B130 there was no way to see what a run would do
 * without doing it and then cleaning the working copy up by hand. B147 made
 * that the *default* — the plan is what a bare run prints, and `--apply` is
 * what writes it. The contract is a negative one — *a run without `--apply`
 * touches nothing* — and a negative is exactly the kind of contract that
 * decays silently, so it is pinned here rather than left to the reviewer.
 *
 * The other half of B130: nothing generates `client/i18n/<locale>/index.json`
 * any more. It was a merged artifact the runtime never read (`ui-i18n.js`
 * fetches the per-module files), regenerated by three scripts, tracked by none
 * — so it floated untracked in every working copy. The generators are gone;
 * this test pins that a full sync does not resurrect one.
 *
 * B132 added a third contract to pin here: the plan's *scope*. Both halves of
 * the sync used to iterate hand-kept lists (a fill list of 8 locales, a prune
 * list of 12, a module list without `follow`); they now derive from
 * `client/i18n/manifest.json`. `planSync()` reports the matrix it covered, so
 * the asymmetry that survives — prune everything, fill only the `ui` modules of
 * the non-reference locales — is asserted rather than re-derived.
 *
 * Run with: node --test tests/i18n-sync-plan.test.js
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

import { planSync } from '../scripts/i18n-sync.js';
import {
  FILL_LOCALES,
  LOCALE_IDS,
  MODULES,
  REFERENCE_LOCALE,
  UI_MODULES,
} from '../scripts/lib/i18n-locales.js';

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const i18nDir = path.join(repoRoot, 'client', 'i18n');
const syncScript = path.join(repoRoot, 'scripts', 'i18n-sync.js');

/**
 * Fingerprint every file under `client/i18n/` — name, size and content hash —
 * so both "an existing file changed" and "a new file appeared" show up as a
 * difference.
 *
 * @returns {Map<string, string>} repo-relative path → sha256 of the contents
 */
function fingerprintI18nTree() {
  const seen = new Map();
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile()) {
        seen.set(
          path.relative(repoRoot, full),
          crypto
            .createHash('sha256')
            .update(fs.readFileSync(full))
            .digest('hex'),
        );
      }
    }
  };
  walk(i18nDir);
  return seen;
}

test('i18n-sync without --apply does not touch a single locale file', () => {
  const before = fingerprintI18nTree();

  const output = execFileSync(process.execPath, [syncScript], {
    cwd: repoRoot,
    encoding: 'utf8',
  });

  const after = fingerprintI18nTree();

  assert.deepEqual(
    [...after.keys()].sort(),
    [...before.keys()].sort(),
    'a plan-only run added or removed files under client/i18n/',
  );
  for (const [file, hash] of before) {
    assert.equal(after.get(file), hash, `a plan-only run rewrote ${file}`);
  }
  assert.match(output, /No files were touched/);
});

test('planSync() reports the edits it would make without writing them', async () => {
  const before = fingerprintI18nTree();
  const plan = await planSync();
  const after = fingerprintI18nTree();

  for (const [file, hash] of before) {
    assert.equal(after.get(file), hash, `planSync() rewrote ${file}`);
  }

  // Every reported edit must actually be an edit: an empty entry would inflate
  // the "N files would change" line the dry run prints.
  for (const edit of plan.edits) {
    assert.ok(
      edit.pruned.length > 0 || edit.filled.length > 0,
      `${edit.locale}/${edit.module}.json is in the plan with nothing to do`,
    );
  }
});

test('no locale ships a merged index.json, and nothing generates one', async () => {
  const stale = [...fingerprintI18nTree().keys()].filter((f) =>
    f.endsWith(`${path.sep}index.json`),
  );
  assert.deepEqual(
    stale,
    [],
    'index.json is a dead artifact (B130) — nothing reads or writes it',
  );

  const planned = (await planSync()).edits.map((e) => e.filePath);
  assert.deepEqual(
    planned.filter((f) => path.basename(f) === 'index.json'),
    [],
    'a sync would write an index.json again',
  );
});

test('the plan covers the manifest matrix, not a list of its own', async () => {
  const { scope } = await planSync();

  assert.deepEqual(scope.locales, LOCALE_IDS);
  assert.deepEqual(scope.modules, MODULES);
  assert.deepEqual(scope.fillLocales, FILL_LOCALES);
  assert.deepEqual(scope.fillModules, UI_MODULES);
  assert.equal(scope.reference, REFERENCE_LOCALE);

  // The prune is the total half: every locale on disk, `follow.json` and the
  // reference locale included. A dead slideType key is dead wherever it sits,
  // and narrowing this half is what stranded it/pl/fi's orphans before B132.
  assert.ok(scope.modules.includes('follow'));
  assert.ok(scope.locales.includes(REFERENCE_LOCALE));
});

test('a fill never targets the reference locale or a deck-loader module', async () => {
  const filled = (await planSync()).edits.filter((e) => e.filled.length > 0);

  // Filling the reference from itself is a no-op at best; the guard is that
  // FILL_LOCALES excludes it, and this is where that shows.
  assert.deepEqual(
    filled.filter((e) => e.locale === REFERENCE_LOCALE).map((e) => e.filePath),
    [],
    'the reference locale was filled from itself',
  );

  // `follow.json` is resolved against the *deck* language, which only ever
  // lands on a Tier-1 locale — copying English into the other ten would write
  // files no loader can reach.
  const offModule = filled
    .filter((e) => !UI_MODULES.includes(e.module))
    .map((e) => `${e.locale}/${e.module}.json`);
  assert.deepEqual(
    offModule,
    [],
    'a non-ui module was filled with English placeholders',
  );

  const offLocale = filled
    .filter((e) => !FILL_LOCALES.includes(e.locale))
    .map((e) => `${e.locale}/${e.module}.json`);
  assert.deepEqual(offLocale, [], 'a locale outside the fill set was filled');
});

test('every planned edit names a manifest locale and module', async () => {
  for (const edit of (await planSync()).edits) {
    assert.ok(
      LOCALE_IDS.includes(edit.locale),
      `${edit.locale}/${edit.module}.json is not a shipped locale`,
    );
    assert.ok(
      MODULES.includes(edit.module),
      `${edit.locale}/${edit.module}.json is not a manifest module`,
    );
  }
});
