/**
 * `i18n:sync` writes a lot: the fill half hands ~2k English keys to every
 * target locale, so before B130 there was no way to see what a run would do
 * without doing it and then cleaning the working copy up by hand. The contract
 * that makes `--dry-run` worth anything is a negative one — *it touches
 * nothing* — and a negative is exactly the kind of contract that decays
 * silently, so it is pinned here rather than left to the reviewer to re-check.
 *
 * The other half of B130: nothing generates `client/i18n/<locale>/index.json`
 * any more. It was a merged artifact the runtime never read (`ui-i18n.js`
 * fetches the per-module files), regenerated by three scripts, tracked by none
 * — so it floated untracked in every working copy. The generators are gone;
 * this test pins that a full sync does not resurrect one.
 *
 * Run with: node --test tests/i18n-sync-dry-run.test.js
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

import { planSync } from '../scripts/i18n-sync.js';

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const i18nDir = path.join(repoRoot, 'client', 'i18n');
const syncScript = path.join(repoRoot, 'scripts', 'i18n-sync.js');

/**
 * Fingerprint every file under `client/i18n/` — name, size and content hash —
 * so both "an existing file changed" and "a new file appeared" show up as a
 * difference.
 *
 * @returns {Map<string, string>} repo-relative path → sha256 of the contents
 */
function fingerprintI18nTree() {
  const seen = new Map();
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile()) {
        seen.set(
          path.relative(repoRoot, full),
          crypto
            .createHash('sha256')
            .update(fs.readFileSync(full))
            .digest('hex'),
        );
      }
    }
  };
  walk(i18nDir);
  return seen;
}

test('i18n-sync --dry-run does not touch a single locale file', () => {
  const before = fingerprintI18nTree();

  const output = execFileSync(process.execPath, [syncScript, '--dry-run'], {
    cwd: repoRoot,
    encoding: 'utf8',
  });

  const after = fingerprintI18nTree();

  assert.deepEqual(
    [...after.keys()].sort(),
    [...before.keys()].sort(),
    'dry run added or removed files under client/i18n/',
  );
  for (const [file, hash] of before) {
    assert.equal(after.get(file), hash, `dry run rewrote ${file}`);
  }
  assert.match(output, /no files were touched/);
});

test('planSync() reports the edits it would make without writing them', () => {
  const before = fingerprintI18nTree();
  const plan = planSync();
  const after = fingerprintI18nTree();

  for (const [file, hash] of before) {
    assert.equal(after.get(file), hash, `planSync() rewrote ${file}`);
  }

  // Every reported edit must actually be an edit: an empty entry would inflate
  // the "N files would change" line the dry run prints.
  for (const edit of plan.edits) {
    assert.ok(
      edit.pruned.length > 0 || edit.filled.length > 0,
      `${edit.locale}/${edit.module}.json is in the plan with nothing to do`,
    );
  }
});

test('no locale ships a merged index.json, and nothing generates one', () => {
  const stale = [...fingerprintI18nTree().keys()].filter((f) =>
    f.endsWith(`${path.sep}index.json`),
  );
  assert.deepEqual(
    stale,
    [],
    'index.json is a dead artifact (B130) — nothing reads or writes it',
  );

  const planned = planSync().edits.map((e) => e.filePath);
  assert.deepEqual(
    planned.filter((f) => path.basename(f) === 'index.json'),
    [],
    'a sync would write an index.json again',
  );
});
