/**
 * `i18n:sync` writes a lot: before B130 there was no way to see what a run
 * would do without doing it and then cleaning the working copy up by hand.
 * B147 made that the *default* — the plan is what a bare run prints, and
 * `--apply` is what writes it. The contract is a negative one — *a run without
 * `--apply` touches nothing* — and a negative is exactly the kind of contract
 * that decays silently, so it is pinned here rather than left to the reviewer.
 *
 * The other half of B130: nothing generates `client/i18n/<locale>/index.json`
 * any more. It was a merged artifact the runtime never read (`ui-i18n.js`
 * fetches the per-module files), regenerated by three scripts, tracked by none
 * — so it floated untracked in every working copy. The generators are gone;
 * this test pins that a full sync does not resurrect one.
 *
 * B132 added a third contract to pin here: the plan's *scope*. Both halves of
 * the sync used to iterate hand-kept lists (a fill list of 8 locales, a prune
 * list of 12, a module list without `follow`); they now derive from
 * `client/i18n/manifest.json`. `planSync()` reports the matrix it covered, so
 * the one asymmetry that survives — prune every locale, strip only the Tier-2
 * ones — is asserted rather than re-derived.
 *
 * B193/D73 turned the second half over: the fill (English values written into
 * every other locale as placeholders) became a **strip** (a Tier-2 value
 * byte-identical to its English one is deleted). Both halves are now deletions,
 * which is a contract of its own — a sync can no longer create a file, and
 * `tests/i18n-coverage.test.js` gates that the strip leaves nothing behind.
 *
 * Run with: node --test tests/i18n-sync-plan.test.js
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

import { planSync } from '../scripts/i18n-sync.js';
import {
  LOCALE_IDS,
  MODULES,
  REFERENCE_LOCALE,
  TIER_1,
  TIER_2,
} from '../scripts/lib/i18n-locales.js';

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);
const i18nDir = path.join(repoRoot, 'client', 'i18n');
const syncScript = path.join(repoRoot, 'scripts', 'i18n-sync.js');

/**
 * Fingerprint every file under `client/i18n/` — name, size and content hash —
 * so both "an existing file changed" and "a new file appeared" show up as a
 * difference.
 *
 * @returns {Map<string, string>} repo-relative path → sha256 of the contents
 */
function fingerprintI18nTree() {
  const seen = new Map();
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile()) {
        seen.set(
          path.relative(repoRoot, full),
          crypto
            .createHash('sha256')
            .update(fs.readFileSync(full))
            .digest('hex'),
        );
      }
    }
  };
  walk(i18nDir);
  return seen;
}

test('i18n-sync without --apply does not touch a single locale file', () => {
  const before = fingerprintI18nTree();

  const output = execFileSync(process.execPath, [syncScript], {
    cwd: repoRoot,
    encoding: 'utf8',
  });

  const after = fingerprintI18nTree();

  assert.deepEqual(
    [...after.keys()].sort(),
    [...before.keys()].sort(),
    'a plan-only run added or removed files under client/i18n/',
  );
  for (const [file, hash] of before) {
    assert.equal(after.get(file), hash, `a plan-only run rewrote ${file}`);
  }
  assert.match(output, /No files were touched/);
});

test('planSync() reports the edits it would make without writing them', async () => {
  const before = fingerprintI18nTree();
  const plan = await planSync();
  const after = fingerprintI18nTree();

  for (const [file, hash] of before) {
    assert.equal(after.get(file), hash, `planSync() rewrote ${file}`);
  }

  // Every reported edit must actually be an edit: an empty entry would inflate
  // the "N files would change" line the dry run prints.
  for (const edit of plan.edits) {
    assert.ok(
      edit.pruned.length > 0 || edit.stripped.length > 0,
      `${edit.locale}/${edit.module}.json is in the plan with nothing to do`,
    );
  }
});

test('no locale ships a merged index.json, and nothing generates one', async () => {
  const stale = [...fingerprintI18nTree().keys()].filter((f) =>
    f.endsWith(`${path.sep}index.json`),
  );
  assert.deepEqual(
    stale,
    [],
    'index.json is a dead artifact (B130) — nothing reads or writes it',
  );

  const planned = (await planSync()).edits.map((e) => e.filePath);
  assert.deepEqual(
    planned.filter((f) => path.basename(f) === 'index.json'),
    [],
    'a sync would write an index.json again',
  );
});

test('the plan covers the manifest matrix, not a list of its own', async () => {
  const { scope } = await planSync();

  assert.deepEqual(scope.locales, LOCALE_IDS);
  assert.deepEqual(scope.modules, MODULES);
  assert.deepEqual(scope.stripLocales, TIER_2);
  assert.equal(scope.reference, REFERENCE_LOCALE);

  // Both halves sweep every module on disk, `follow.json` included: a dead
  // slideType key and a carbon copy of English are dead weight wherever they
  // sit. Narrowing the prune by module is what stranded it/pl/fi's orphans
  // before B132, and the strip is deliberately not narrowed either — which is
  // why the scope has no per-half module list to disagree with itself.
  assert.ok(scope.modules.includes('follow'));
  assert.ok(scope.locales.includes(REFERENCE_LOCALE));
});

test('a strip never touches the reference locale or a Tier-1 one', async () => {
  const stripped = (await planSync()).edits.filter(
    (e) => e.stripped.length > 0,
  );

  // Tier 1 is complete-or-the-build-fails, and a Dutch value that happens to
  // equal the English can be real Dutch ("Export", "Status") — so `nl` and the
  // reference itself both stay out. TIER_2 is the whole of that policy (D73).
  const offLocale = stripped
    .filter((e) => !TIER_2.includes(e.locale))
    .map((e) => `${e.locale}/${e.module}.json`);
  assert.deepEqual(
    offLocale,
    [],
    'a Tier-1 locale had values stripped as carbon copies',
  );
  assert.ok(TIER_1.includes(REFERENCE_LOCALE));
});

test('every edit a sync plans is a deletion — a file is never created', async () => {
  // Both halves remove keys now (B193/D73). The fill half used to write a file
  // into existence for a locale that lacked the module; nothing does, so a
  // planned path is always a path already on disk.
  for (const edit of (await planSync()).edits) {
    assert.ok(
      fs.existsSync(edit.filePath),
      `${edit.filePath} is in the plan but does not exist`,
    );
    for (const key of [...edit.pruned, ...edit.stripped]) {
      assert.ok(
        !(key in edit.data),
        `${edit.locale}/${edit.module}.json still holds ${key} after the plan`,
      );
    }
  }
});

test('every planned edit names a manifest locale and module', async () => {
  for (const edit of (await planSync()).edits) {
    assert.ok(
      LOCALE_IDS.includes(edit.locale),
      `${edit.locale}/${edit.module}.json is not a shipped locale`,
    );
    assert.ok(
      MODULES.includes(edit.module),
      `${edit.locale}/${edit.module}.json is not a manifest module`,
    );
  }
});
