/**
 * Where `themeVarsCssText()` declares each theme var, which is not a cosmetic
 * question.
 *
 * A custom property's `var()` references are substituted where that property is
 * *computed*, not where it is read. `--t-slide-gradient-bg` — generated by
 * `normalizeTheme()` for any theme with `gradient.enabled` and no literal of its
 * own — reads `var(--g1x)` … `var(--g3y)`, and those only ever exist on the slide
 * root. Declared on the stage it is guaranteed-invalid, inherits down as invalid,
 * and every `background: var(--t-slide-gradient-bg, transparent)` layer falls back
 * to nothing. That is what shipped until 2026-07-31: the per-slide jitter from
 * `gradientVarsForSlide()` had never reached a pixel in any server-rendered
 * document.
 *
 * The end-to-end proof lives in `export-gradient-raster.test.js` (measured in
 * Chrome, where the layer either paints or does not). These are the cheap
 * structural guards that fail first, without a browser.
 *
 * Run with: node --test tests/theme-vars-css-scope.test.js
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { themeVarsCssText } from '../server/utils/themes.js';
import { normalizeTheme } from '../shared/theme-normalize.js';

/** The declarations inside the first rule whose selector matches exactly. */
function blockFor(css, selector) {
  const rules = [...css.matchAll(/([^{}]+)\{([^{}]*)\}/g)];
  const hit = rules.find((m) => m[1].trim() === selector);
  return hit ? hit[2] : null;
}

test('the generated gradient is declared on the slide root, not on the stage', () => {
  const theme = normalizeTheme({
    id: 'grad',
    label: 'Grad',
    gradient: { enabled: true },
    cssVars: {
      '--t-quote-author-color': '#7dd3fc',
      '--t-color-accent': '#38bdf8',
      '--t-slide-bg-mist': '#27272a',
    },
  });
  // Precondition: this theme is the generated-gradient case the scoping exists for.
  assert.match(theme.cssVars['--t-slide-gradient-bg'], /var\(--g1x\)/);

  const css = themeVarsCssText(theme);
  const stage = blockFor(css, '.ps-theme');
  const slide = blockFor(css, '.ps-theme .slide');

  assert.ok(stage, 'the stage block is still emitted');
  assert.doesNotMatch(
    stage,
    /--t-slide-gradient-bg\s*:/,
    'declared on the stage it cannot see --g1x and is guaranteed-invalid',
  );
  assert.ok(slide, 'a slide-root block carries it instead');
  assert.match(slide, /--t-slide-gradient-bg\s*:\s*radial-gradient\(/);

  // Everything else stays on the stage, the gate above all: the export paths
  // switch these layers off with a later `.ps-theme { --t-gradient-enabled: 0 }`,
  // which only wins if the theme's own declaration sits at the same specificity.
  assert.match(stage, /--t-gradient-enabled\s*:\s*1/);
  assert.match(stage, /--t-color-accent\s*:/);
});

test('the slide-root block is scoped to the caller-supplied stage selector', () => {
  // Two themed stages on one page must not paint each other's gradient — the
  // same reason the vars block is scoped at all.
  const theme = normalizeTheme({
    id: 'grad',
    label: 'Grad',
    gradient: { enabled: true },
    cssVars: {
      '--t-quote-author-color': '#7dd3fc',
      '--t-color-accent': '#38bdf8',
      '--t-slide-bg-mist': '#27272a',
    },
  });
  const css = themeVarsCssText(theme, { selector: '#stage.ps-theme' });
  assert.ok(blockFor(css, '#stage.ps-theme .slide'));
  assert.equal(blockFor(css, '.slide'), null, 'never unscoped');
});

test('a theme without a gradient emits no slide-root block at all', () => {
  const theme = normalizeTheme({
    id: 'plain',
    label: 'Plain',
    cssVars: { '--t-color-accent': '#38bdf8' },
  });
  const css = themeVarsCssText(theme);
  assert.equal(theme.cssVars['--t-slide-gradient-bg'], undefined);
  assert.equal(blockFor(css, '.ps-theme .slide'), null);
  assert.match(blockFor(css, '.ps-theme'), /--t-color-accent\s*:/);
});

test("a theme's own literal gradient is scoped the same way", () => {
  // A literal needs no substitution, so it would resolve on the stage too. It
  // still moves, because a theme that later switches to reading `--g1x` must not
  // silently go invalid again — and because one rule beats two shapes to reason
  // about.
  const theme = normalizeTheme({
    id: 'literal',
    label: 'Literal',
    gradient: { enabled: true },
    cssVars: {
      '--t-slide-gradient-bg':
        'radial-gradient(circle at 20% 30%, rgba(1,2,3,0.9) 0%, rgba(1,2,3,0) 70%), #06090b',
    },
  });
  const css = themeVarsCssText(theme);
  assert.doesNotMatch(blockFor(css, '.ps-theme'), /--t-slide-gradient-bg\s*:/);
  assert.match(blockFor(css, '.ps-theme .slide'), /--t-slide-gradient-bg\s*:/);
});
