/**
 * Vendor hls.js into client/vendor/ so a deck that plays an HLS stream loads
 * the player from this server instead of jsDelivr.
 *
 * `client/lib/slide-runtime/ensure-hls.js` used to inject
 * `cdn.jsdelivr.net/npm/hls.js@1/dist/hls.min.js` the first time a reader hit a
 * stream that needed it — a lazy load, but still a third-party origin the CSP
 * had to keep open on every render path, whether or not any deck used it
 * (D51(a) / B119's sibling item B120). hls.js is an ordinary pinnable library
 * with no service behind it, so vendoring is the whole fix: the origin leaves
 * `THIRD_PARTY_ORIGINS` in the same change, and `script-src` narrows with it.
 *
 * The version is pinned by package-lock.json with an integrity hash — the same
 * reproducibility story as DOMPurify and pdf.js, without a second lock file.
 * This script only copies the already-verified dist file into the tree.
 *
 * **The source map is deliberately left behind.** `hls.min.js.map` is 2.7 MB,
 * four times the library itself, to give devtools readable frames in a
 * dependency nobody here debugs. Same trade pdf.js makes (its maps stay out
 * too). The `//# sourceMappingURL=` comment is stripped from the copy so the
 * browser does not chase a file that is not there.
 *
 * Run via `npm run vendor:hls` (also part of postinstall).
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

const srcDir = path.join(repoRoot, 'node_modules', 'hls.js');
const destDir = path.join(repoRoot, 'client', 'vendor', 'hls');

/** The one file the runtime loads. */
const FILE = 'hls.min.js';

async function main() {
  let version;
  try {
    const pkg = JSON.parse(
      await fs.readFile(path.join(srcDir, 'package.json'), 'utf8'),
    );
    version = pkg.version;
  } catch {
    throw new Error(
      'Could not read node_modules/hls.js/package.json. Did npm install run?',
    );
  }

  await fs.mkdir(destDir, { recursive: true });

  const source = await fs.readFile(path.join(srcDir, 'dist', FILE), 'utf8');
  // Strip the trailing sourceMappingURL: the map is not vendored (see docblock),
  // and a dangling reference is a 404 in every reader's devtools.
  const stripped = `${source.replace(/\n?\/\/# sourceMappingURL=.*\s*$/, '')}\n`;
  await fs.writeFile(path.join(destDir, FILE), stripped, 'utf8');

  const files = [
    {
      path: FILE,
      sha256: createHash('sha256').update(stripped).digest('hex'),
    },
  ];

  await fs.writeFile(
    path.join(destDir, 'manifest.json'),
    `${JSON.stringify(
      {
        $comment:
          'Generated by `npm run vendor:hls`. The version is whatever package-lock.json resolves; do not hand-edit.',
        source: 'hls.js',
        version,
        files,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  // eslint-disable-next-line no-console
  console.log(
    `Vendored hls.js ${version} to ${path.relative(repoRoot, destDir)}`,
  );
}

await main();
