/**
 * Vendor pdf.js into client/vendor/ so PDF import parses an uploaded file with
 * a build this repo pins, instead of one a CDN happens to serve.
 *
 * `server/render/pdf-to-images.js` opens a user-uploaded PDF inside the shared
 * headless browser. It used to hand that browser a hardcoded
 * `cdnjs.cloudflare.com/…/pdf.js/3.11.174/pdf.min.js`: a third party with
 * script rights in the process that renders every deck, pinned by nothing —
 * `pdfjs-dist` was not even a dependency. It is one now, so package-lock.json
 * pins it with an integrity hash and `npm audit` can see it.
 *
 * **Why the version is pinned exactly.** `pdf-parse` (the text extractor used
 * elsewhere in import) depends on `pdfjs-dist` at an exact version of its own.
 * Matching it lets npm keep **one** copy in the tree; a `^` range resolves to
 * the newest 5.x, npm nests pdf-parse's pin underneath, and the install grows by
 * ~70 MB (a second pdfjs-dist plus a second `@napi-rs/canvas` native binary) for
 * two static files. `tests/pdf-import-self-hosted.test.js` fails when the two
 * drift apart, which is the moment to re-align and re-vendor.
 *
 * Only the two build files are copied. `standard_fonts/` (0.8 MB) and `cmaps/`
 * (1.7 MB) stay out: pdf.js only fetches those when `standardFontDataUrl` /
 * `cMapUrl` are set, which the harness has never done, so vendoring them would
 * change what an imported PDF looks like rather than where it comes from.
 *
 * Run via `npm run vendor:pdfjs` (also part of postinstall).
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

/** The files the harness page loads, and nothing else. */
const FILES = ['pdf.min.mjs', 'pdf.worker.min.mjs'];

async function readVersion(pkgName) {
  try {
    const pkg = JSON.parse(
      await fs.readFile(
        path.join(repoRoot, 'node_modules', pkgName, 'package.json'),
        'utf8',
      ),
    );
    return pkg.version;
  } catch {
    throw new Error(
      `Could not read node_modules/${pkgName}/package.json. Did npm install run?`,
    );
  }
}

async function copyWithHash(src, destDir, relPath) {
  const dest = path.join(destDir, relPath);
  await fs.mkdir(path.dirname(dest), { recursive: true });
  const buf = await fs.readFile(src);
  await fs.writeFile(dest, buf);
  return {
    path: relPath,
    sha256: createHash('sha256').update(buf).digest('hex'),
  };
}

async function main() {
  const version = await readVersion('pdfjs-dist');
  const srcDir = path.join(repoRoot, 'node_modules', 'pdfjs-dist', 'build');
  const destDir = path.join(repoRoot, 'client', 'vendor', 'pdfjs');
  // Removed first, so a file that leaves the list leaves the tree — a copy can
  // never produce a deletion, and an orphan regenerates byte-identical forever.
  await fs.rm(destDir, { recursive: true, force: true });

  const files = [];
  for (const name of FILES) {
    files.push(await copyWithHash(path.join(srcDir, name), destDir, name));
  }

  await fs.writeFile(
    path.join(destDir, 'manifest.json'),
    `${JSON.stringify(
      {
        $comment:
          'Generated by `npm run vendor:pdfjs`. The version is whatever package-lock.json resolves; do not hand-edit.',
        source: 'pdfjs-dist',
        version,
        files,
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  // eslint-disable-next-line no-console
  console.log(
    `Vendored pdf.js ${version} (${files.length} files) to client/vendor/pdfjs/`,
  );
}

await main();
